sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 20001016
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tKT7EpH4XtsuC9CWXS5
    access-key-secret: uQLWo5sTWS329HaZegprNxWn01c1N3
    bucket-name: web-stores
  redis:
    host: localhost
    port: 6379
    password: 20001016
    database: 1